//console.log("Equality test with string:", "Mango" === "Mango");
//console.log("Inequality test with strings:",("Mango" as string) != "Apple");
console.log("Lower Case function test: ", "HELLO".toLowerCase() === "hello");
console.log("Equality test with numbers: ", 27 === 27);
console.log("Inequality testwith numbers: ", 27 != 37);
console.log("Greater than test: ", 10 > 5);
console.log("less than test: ", 5 < 10);
console.log("Greater than an equal to test: ", 27 >= 27);
console.log("less than or equal to: ", 5 <= 10);
console.log("And operator test: ", 5 === 5 && 10 > 5);
console.log("or operator test: ", 5 === 5 || 10 < 5);
var names = ["zaryab", "mama", "baba", "bhai",];
console.log('test "zaryab"in the array: ', names.includes("zaryab"));
var names = ["zaryab", "mama", "baba", "bhai",];
console.log('test  "yousha" is not in the array: ', !names.includes("yousha"));
